GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlaWpvbmEiLCJpZCI6IjYzMGRlY2Y2ZDY2NWMwMmQ5MWMxNmQ2MiIsImlhdCI6MTY2MjAzNDYzOSwiZXhwIjoxNjYyMDM4MjM5fQ.zM07FlxPxWBR7Zq2T7M2xQC5zX6d2sntXq0M3QzWc5Y

